import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react-swc'
import tailwindcss from "@tailwindcss/vite"
import { tanstackRouter } from '@tanstack/router-plugin/vite'

import fs from 'fs';
import path from 'path';

function firebaseConfigWrite() {
  const FIREBASE_CONFIG_FILE = path.resolve(__dirname, './src/config/firebase-config.ts');

  const FIREBASE_CONFIG_ENV_VAR = 'FIREBASE_CONFIG';

  try {
    if (!process.env[FIREBASE_CONFIG_ENV_VAR]) {
      // throw new Error(`Missing required environment variable: ${FIREBASE_CONFIG_ENV_VAR}. Please set it.`);
      return
    }

    const firebaseConfigContent = `
// This file is auto-generated by vite.config.js
// Do not edit this file directly.

export const firebaseConfig = ${process.env[FIREBASE_CONFIG_ENV_VAR]};
`;
    // todo: dont write if exists

    fs.writeFileSync(FIREBASE_CONFIG_FILE, firebaseConfigContent.trim());
    console.log(`Generated ${FIREBASE_CONFIG_FILE} successfully!`);

  } catch (error) {
    if (error instanceof Error)
      console.error(`Error generating Firebase config file: ${error.message}`);
    process.exit(1);
  }
}
firebaseConfigWrite()
// https://vite.dev/config/
export default defineConfig({
  plugins: [
    tanstackRouter({
      target: 'react',
      autoCodeSplitting: true,
    }),
    react(), tailwindcss()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
})
